name: Klipper Config Check

on:
  workflow_dispatch:  # позволяет запуск вручную из GitHub UI

jobs:
  check-klipper-config:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y libffi-dev build-essential

      - name: Clone Klipper
        run: |
          git clone https://github.com/Klipper3d/klipper.git

      - name: Install Klipper Python dependencies
        run: |
          pip install -r klipper/scripts/klippy-requirements.txt

      - name: Run Klipper config check
        run: |
          python3 klipper/klippy/klippy.py printer.cfg -i /tmp
