name: Klipper Config Check

on:
  push:
    paths:
      - '**.cfg'
  pull_request:
    paths:
      - '**.cfg'

jobs:
  check-klipper-config:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install klipper dependencies
        run: |
          sudo apt update
          sudo apt install -y libffi-dev build-essential
          git clone https://github.com/Klipper3d/klipper.git
          cd klipper
          make menuconfig  # (опционально, если нужен sim mode)
          make
          pip install -r scripts/klippy-requirements.txt

      - name: Run config syntax check
        run: |
          cd klipper
          python3 klippy/klippy.py ../printer.cfg -i /tmp
