name: 🔍 Проверка конфигурации (вручную)

on:
  workflow_dispatch:  # ← добавляет кнопку «Run workflow» в GitHub Actions

jobs:
  minimal-check:
    runs-on: ubuntu-latest
    steps:
      - name: 🛎️ Клонирование репозитория
        uses: actions/checkout@v3

      - name: 📂 Проверка обязательных файлов
        run: |
          echo "Проверяем наличие важных файлов..."
          test -f printor.cfg || (echo "❌ Не найден: printer.cfg" && exit 1)
          test -f moonraker.conf || (echo "❌ Не найден: moonraker.conf" && exit 1)
          test -f shell_command.cfg || (echo "❌ Не найден: shell_command.cfg" && exit 1)
          echo "✅ Все нужные файлы на месте!"
